# Generated by Django 3.1.6 on 2021-04-24 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0033_merge_20210420_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.supply'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
