# Generated by Django 3.1.6 on 2021-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20210424_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='reservation',
            name='traveller',
            field=models.IntegerField(default=''),
        ),
    ]
