# Generated by Django 3.1.6 on 2021-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210425_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='traveller',
            field=models.IntegerField(default=None),
        ),
    ]
