# Generated by Django 3.1.6 on 2021-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210428_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default=False, max_length=11),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='traveller',
            field=models.IntegerField(default=False),
        ),
    ]
