# Generated by Django 3.1.6 on 2021-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20210425_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='traveller',
            field=models.IntegerField(default=None),
        ),
    ]
