# Generated by Django 3.1.6 on 2021-05-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_message_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='price',
        ),
    ]
