# Generated by Django 3.1.6 on 2021-05-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_supply_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='drop_of_before',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='pick_up_from',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
